# Generated by Django 5.1 on 2024-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrpyt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='uploaded_image',
            field=models.ImageField(default='', upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='encryptedimage',
            name='encrypted_image_path',
            field=models.ImageField(default='', upload_to='encrypted_images/'),
        ),
    ]
