# Generated by Django 5.1 on 2024-08-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrpyt', '0002_encryptedimage_uploaded_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedimage',
            name='encrypted_image_path',
            field=models.CharField(max_length=250),
        ),
    ]
